server:
  servlet:
    session:
      timeout: 24h
  #    context-path: /takeout
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/takeout?rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  redis:
    host: localhost
    database: 0
  cache:
    type: redis
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 2170850451@qq.com
    password: lkkpqvtyexnrebjf
    test-connection: false
    properties.mail.smtp.auth: false
    properties.mail.debug: false
    properties.mail.mime.splitlongparameters: false
    default-encoding: UTF-8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id